name: "Mirror repos"

on:
  push:
    branches: [ main ]
  schedule:
    # Run everyday at 3:37 AM UTC
    - cron: '37 3 * * *'
  workflow_dispatch:

jobs:
  # Add one of these jobs for every repo that needs to be mirrored
  tandem-devkit:
    uses: ./.github/workflows/reusable-workflow-mirror-repo.yml
    secrets: inherit
    with:
      source_repo_url: "https://codeberg.org/uFahrrad/tandem-devkit"
      destination_repo_name: "tandem-devkit"
